import * as fs from 'fs';
import * as path from 'path';

// Path constants relative to project root
const NEWS_JSON_PATH = path.join(__dirname, '..', 'src', 'data', 'news.json');
const DAILY_DIR_PATH = path.join(__dirname, '..', 'src', 'pages', 'daily');

interface NewsItem {
  id: string;
  source: string;
  title: string;
  date: string;
  url: string;
}

function readNewsJson(): NewsItem[] {
  try {
    if (fs.existsSync(NEWS_JSON_PATH)) {
      const content = fs.readFileSync(NEWS_JSON_PATH, 'utf-8');
      return JSON.parse(content);
    }
  } catch (error) {
    console.error('Error reading news.json:', error);
  }
  return [];
}

function getYesterday(): Date {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  yesterday.setHours(0, 0, 0, 0);
  return yesterday;
}

function getToday(): Date {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return today;
}

function filterYesterdayItems(items: NewsItem[]): NewsItem[] {
  const yesterday = getYesterday();
  const today = getToday();
  
  return items.filter(item => {
    const itemDate = new Date(item.date);
    return itemDate >= yesterday && itemDate < today;
  });
}

function groupBySource(items: NewsItem[]): Map<string, NewsItem[]> {
  const grouped = new Map<string, NewsItem[]>();
  
  for (const item of items) {
    const existing = grouped.get(item.source) || [];
    existing.push(item);
    grouped.set(item.source, existing);
  }
  
  return grouped;
}

function formatDate(date: Date): string {
  return date.toISOString().split('T')[0];
}

function generateMarkdown(grouped: Map<string, NewsItem[]>, date: Date): string {
  const dateStr = formatDate(date);
  let markdown = `---
title: "AI Pulse Daily Summary - ${dateStr}"
date: ${dateStr}
---

# AI Pulse Daily Summary

**Date:** ${dateStr}

`;

  if (grouped.size === 0) {
    markdown += `> No news items were collected yesterday.\n\n`;
    return markdown;
  }

  markdown += `## Summary\n\n`;
  markdown += `Total updates collected: ${Array.from(grouped.values()).reduce((sum, items) => sum + items.length, 0)}\n\n`;

  // Sort sources alphabetically
  const sortedSources = Array.from(grouped.keys()).sort();

  for (const source of sortedSources) {
    const items = grouped.get(source)!;
    markdown += `## ${source}\n\n`;
    
    for (const item of items) {
      markdown += `- **${item.title}**\n`;
      markdown += `  - [View](${item.url})\n`;
      markdown += `  - _Added: ${new Date(item.date).toLocaleTimeString()}_\n\n`;
    }
  }

  markdown += `---\n\n`;
  markdown += `_This summary was automatically generated by the AI Pulse monitoring system._\n`;

  return markdown;
}

function writeToDaily(content: string, date: Date): string {
  // Ensure daily directory exists
  if (!fs.existsSync(DAILY_DIR_PATH)) {
    fs.mkdirSync(DAILY_DIR_PATH, { recursive: true });
  }

  const dateStr = formatDate(date);
  const filename = `${dateStr}.md`;
  const filepath = path.join(DAILY_DIR_PATH, filename);

  fs.writeFileSync(filepath, content);
  return filepath;
}

async function main() {
  console.log('Generating daily summary...\n');

  // Read all news items
  const allNews = readNewsJson();
  console.log(`Total items in news.json: ${allNews.length}`);

  // Filter yesterday's items
  const yesterday = getYesterday();
  const yesterdayItems = filterYesterdayItems(allNews);
  console.log(`Items from yesterday (${formatDate(yesterday)}): ${yesterdayItems.length}`);

  // Group by source
  const grouped = groupBySource(yesterdayItems);
  console.log(`Sources with updates: ${grouped.size}`);

  // Generate markdown
  const markdown = generateMarkdown(grouped, yesterday);

  // Write to daily folder
  const filepath = writeToDaily(markdown, yesterday);
  console.log(`\nSummary written to: ${filepath}`);

  // Output the markdown for review
  console.log('\n--- Generated Summary ---\n');
  console.log(markdown);
}

main().catch(console.error);
